export const activityTypes = {
    FETCH_ACTIVITY_START:"FETCH_ACTIVITY_START",
    FETCH_ACTIVITY_SUCCESS:"FETCH_ACTIVITY_SUCCESS",
    FETCH_ACTIVITY_FAIL:"FETCH_ACTIVITY_FAIL",

    CREATE_ACTIVITY_START:"CREATE_ACTIVITY_START",
    CREATE_ACTIVITY_SUCCESS:"CREATE_ACTIVITY_SUCCESS",
    CREATE_ACTIVITY_FAILURE:"CREATE_ACTIVITY_FAILURE",
    RESET_ACTIVITY:"RESET_ACTIVITY",

}