export const crewTypes = {
    FETCH_CREW_START: "FETCH_CREW_START",
    FETCH_CREW_SUCCESS: "FETCH_CREW_SUCCESS",
    FETCH_CREW_FAIL: "FETCH_CREW_FAIL",

    CREATE_CREW_START: "CREATE_CREW_START",
    CREATE_CREW_SUCCESS: "CREATE_CREW_SUCCESS",
    CREATE_CREW_FAILURE: "CREATE_CREW_FAILURE",

    UPDATE_CREW_START: "UPDATE_CREW_START",
    UPDATE_CREW_SUCCESS: "UPDATE_CREW_SUCCESS",
    UPDATE_CREW_FAILURE: "UPDATE_CREW_FAILURE",

    DELETE_CREW_START: "DELETE_CREW_START",
    DELETE_CREW_SUCCESS: "DELETE_CREW_SUCCESS",
    DELETE_CREW_FAILURE: "DELETE_CREW_FAILURE",

    TOGGLE_POPUP_UPDATE: "TOGGLE_POPUP_UPDATE",
    POPUP_DELETE: "POPUP_DELETE",

    CREW_INVITION_SUCCESS: " CREW_INVITION_SUCCESS",
    CREW_INVITION_FAILURE: " CREW_INVITION_FAILURE",


    RESET_CREW: "RESET_CREW",

    TOGGLE_POPUP: "TOGGLE_POPUP",
}