export const messageTypes = {
    FETCH_MESSAGE_START:"FETCH_MESSAGE_START",
    FETCH_MESSAGE_SUCCESS:"FETCH_MESSAGE_SUCCESS",
    FETCH_MESSAGE_FAIL:"FETCH_MESSAGE_FAIL",

    CREATE_MESSAGE_START:"CREATE_MESSAGE_START",
    CREATE_MESSAGE_SUCCESS:"CREATE_MESSAGE_SUCCESS",
    CREATE_MESSAGE_FAILURE:"CREATE_MESSAGE_FAILURE",
    RESET_MESSAGE:"RESET_MESSAGE",

}