export const PaymentTypes = {
    FETCH_SUCCESSPAYMENT_START: "FETCH_SUCCESSPAYMENT_START",
    FETCH_SUCCESSPAYMENT_SUCCESS: "FETCH_SUCCESSPAYMENT_SUCCESS",
    FETCH_SUCCESSPAYMENT_FAIL: "FETCH_SUCCESSPAYMENT_FAIL",

    FETCH_CANCELPAYMENT_START: "FETCH_CANCELPAYMENT_START",
    FETCH_CANCELPAYMENT_SUCCESS: "FETCH_CANCELPAYMENT_SUCCESS",
    FETCH_CANCELPAYMENT_FAIL: "FETCH_CANCELPAYMENT_FAIL",

}