export const propertyTypes = {
    FETCH_PROPERTY_START: "FETCH_PROPERTY_START",
    FETCH_PROPERTY_SUCCESS: "FETCH_PROPERTY_SUCCESS",
    FETCH_PROPERTY_FAIL: "FETCH_PROPERTY_FAIL",

    CREATE_PROPERTY_START: "CREATE_PROPERTY_START",
    CREATE_PROPERTY_SUCCESS: "CREATE_PROPERTY_SUCCESS",
    CREATE_PROPERTY_FAILURE: "CREATE_PROPERTY_FAILURE",

    UPDATE_PROPERTY_START: "UPDATE_PROPERTY_START",
    UPDATE_PROPERTY_SUCCESS: "UPDATE_PROPERTY_SUCCESS",
    UPDATE_PROPERTY_FAILURE: "UPDATE_PROPERTY_FAILURE",

    DELETE_PROPERTY_START: "DELETE_PROPERTY_START",
    DELETE_PROPERTY_SUCCESS: "DELETE_PROPERTY_SUCCESS",
    DELETE_PROPERTY_FAILURE: "DELETE_PROPERTY_FAILURE",

    RESET_PROPERTY: "RESET_PROPERTY",

    TOGGLE_POPUP: "TOGGLE_POPUP",

}